global:
  scrape_interval: 300s

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 300s

    honor_labels: true
    metrics_path: '/metrics'

    params:
      'match[]':
        - '{job="gateway"}'
        - '{__name__=~"gateway.*"}'

    static_configs:
      - targets:
        - '<rpi_ip_address>:8081'